using System.Text;
using System.Text.Json;
using ServiceMap.Core.Models;

namespace ServiceMap.Reporting;

/// <summary>
/// Generates target-cloud firewall rule definitions from observed flows:
/// AWS Security Group and Azure NSG, each as Terraform plus a neutral JSON.
/// Rules are derived per (protocol, service port) with the distinct observed
/// peers as /32 sources — a starting point for the landing-zone team, not a
/// finished policy (review before applying; prefer FQDN/team CIDRs where known).
/// </summary>
public static class CloudRuleGenerator
{
    private const int MaxPeersPerRule = 40;

    private sealed record RuleLine(string Proto, int Port, List<string> Peers, string Service, long Samples);

    /// <summary>Returns file name → content for the cloud-rules folder of a dossier.</summary>
    public static Dictionary<string, string> Generate(DossierData d)
    {
        var ingress = Collapse(d.Inbound, inbound: true);
        var egress = Collapse(d.Outbound, inbound: false);
        var name = Sanitize(d.MachineName);

        return new Dictionary<string, string>
        {
            ["aws-security-group.tf"] = AwsTf(name, d.MachineName, ingress, egress),
            ["azure-nsg.tf"] = AzureTf(name, d.MachineName, ingress, egress),
            ["cloud-rules.json"] = NeutralJson(d.MachineName, ingress, egress)
        };
    }

    private static List<RuleLine> Collapse(IReadOnlyList<ConnectionAggregate> flows, bool inbound)
    {
        return flows
            .Where(f => !string.IsNullOrEmpty(f.RemoteAddress) && f.RemoteAddress.Contains('.'))  // IPv4 only
            .GroupBy(f => (Proto: f.Protocol.ToString().ToLowerInvariant(),
                           Port: inbound ? f.LocalPort : f.RemotePort))
            .Where(g => g.Key.Port > 0)
            .Select(g => new RuleLine(
                g.Key.Proto, g.Key.Port,
                g.Select(f => f.RemoteAddress).Distinct().OrderBy(x => x).ToList(),
                g.Select(f => f.ServiceOrProcess).Where(s => s.Length > 0).Distinct().FirstOrDefault() ?? "",
                g.Sum(f => f.SampleCount)))
            .OrderBy(r => r.Port)
            .ToList();
    }

    private static string AwsTf(string name, string machine, List<RuleLine> ingress, List<RuleLine> egress)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Carrier DependenSee from observed traffic - REVIEW BEFORE APPLYING.");
        sb.AppendLine($"# Machine: {machine}. Peers are observed /32s; widen to subnets/SG references deliberately.");
        sb.AppendLine($"resource \"aws_security_group\" \"{name}\" {{");
        sb.AppendLine($"  name        = \"{name}-migrated\"");
        sb.AppendLine($"  description = \"Observed flows for {machine}\"");
        sb.AppendLine("  vpc_id      = var.vpc_id");
        sb.AppendLine();
        foreach (var r in ingress)
        {
            sb.AppendLine("  ingress {");
            sb.AppendLine($"    description = \"{Esc(r.Service)} ({r.Samples} samples)\"");
            sb.AppendLine($"    from_port   = {r.Port}");
            sb.AppendLine($"    to_port     = {r.Port}");
            sb.AppendLine($"    protocol    = \"{r.Proto}\"");
            sb.AppendLine($"    cidr_blocks = [{Cidrs(r.Peers)}]");
            sb.AppendLine("  }");
        }
        foreach (var r in egress)
        {
            sb.AppendLine("  egress {");
            sb.AppendLine($"    description = \"{Esc(r.Service)} ({r.Samples} samples)\"");
            sb.AppendLine($"    from_port   = {r.Port}");
            sb.AppendLine($"    to_port     = {r.Port}");
            sb.AppendLine($"    protocol    = \"{r.Proto}\"");
            sb.AppendLine($"    cidr_blocks = [{Cidrs(r.Peers)}]");
            sb.AppendLine("  }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string AzureTf(string name, string machine, List<RuleLine> ingress, List<RuleLine> egress)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Carrier DependenSee from observed traffic - REVIEW BEFORE APPLYING.");
        sb.AppendLine($"resource \"azurerm_network_security_group\" \"{name}\" {{");
        sb.AppendLine($"  name                = \"{name}-migrated\"");
        sb.AppendLine("  location            = var.location");
        sb.AppendLine("  resource_group_name = var.resource_group_name");
        sb.AppendLine();
        var priority = 100;
        foreach (var (r, dir) in ingress.Select(r => (r, "Inbound")).Concat(egress.Select(r => (r, "Outbound"))))
        {
            sb.AppendLine("  security_rule {");
            sb.AppendLine($"    name                       = \"{name}-{dir.ToLowerInvariant()}-{r.Proto}-{r.Port}\"");
            sb.AppendLine($"    priority                   = {priority}");
            sb.AppendLine($"    direction                  = \"{dir}\"");
            sb.AppendLine("    access                     = \"Allow\"");
            sb.AppendLine($"    protocol                   = \"{Cap(r.Proto)}\"");
            sb.AppendLine("    source_port_range          = \"*\"");
            sb.AppendLine($"    destination_port_range     = \"{r.Port}\"");
            if (dir == "Inbound")
            {
                sb.AppendLine($"    source_address_prefixes    = [{Cidrs(r.Peers)}]");
                sb.AppendLine("    destination_address_prefix = \"*\"");
            }
            else
            {
                sb.AppendLine("    source_address_prefix      = \"*\"");
                sb.AppendLine($"    destination_address_prefixes = [{Cidrs(r.Peers)}]");
            }
            sb.AppendLine("  }");
            priority += 10;
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string NeutralJson(string machine, List<RuleLine> ingress, List<RuleLine> egress)
    {
        var model = new
        {
            machine,
            generated_utc = DateTime.UtcNow,
            note = "Derived from observed traffic; review before applying.",
            ingress = ingress.Select(ToJson),
            egress = egress.Select(ToJson)
        };
        return JsonSerializer.Serialize(model, new JsonSerializerOptions { WriteIndented = true });

        static object ToJson(RuleLine r) => new
        {
            protocol = r.Proto,
            port = r.Port,
            service = r.Service,
            samples = r.Samples,
            peers = r.Peers.Take(MaxPeersPerRule).Select(p => p + "/32"),
            peers_truncated = r.Peers.Count > MaxPeersPerRule ? r.Peers.Count - MaxPeersPerRule : 0
        };
    }

    private static string Cidrs(List<string> peers)
    {
        var shown = peers.Take(MaxPeersPerRule).Select(p => $"\"{p}/32\"");
        var txt = string.Join(", ", shown);
        return peers.Count > MaxPeersPerRule
            ? txt + $" /* +{peers.Count - MaxPeersPerRule} more observed - summarize to CIDRs */"
            : txt;
    }

    private static string Esc(string s) => s.Replace("\"", "'");
    private static string Cap(string s) => s.Length == 0 ? s : char.ToUpperInvariant(s[0]) + s[1..];

    private static string Sanitize(string name)
    {
        var chars = name.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        var s = new string(chars).Trim('-');
        return s.Length > 0 ? s : "server";
    }
}
